language: python

python:
  "3.6.5"

install:
 - pip install -r requirements.txt

services:
  postgresql

before_script:
 - export APP_SETTINGS=testing
 - psql -c 'create database test_db;' -U postgres
 - psql -c "ALTER USER postgres WITH PASSWORD '1234';" -U postgres 
env: 
 - DATABASE_URL_TEST="dbname='test_db' user='postgres' host='localhost' password='1234'"

script:
 - pytest --cov-report term-missing --cov=app
  
after_success:
 - coveralls
